namespace Dataverse.Core.Services;

using System.Text.Json;
using System.Xml.Linq;
using Dataverse.Core.Clients;
using Dataverse.Core.Json;
using Dataverse.Core.Models;
using Microsoft.Extensions.Logging;

/// <summary>
/// Reads and edits model-driven forms (<c>systemform</c>).
/// </summary>
/// <remarks>
/// Everything here exists because FormXML is not workable by hand. The read side turns it into a
/// tree; the write side hides the details that are easy to get wrong and produce errors far from
/// their cause:
/// <list type="bullet">
/// <item>A code component sits in a cell as a <b>generic</b> control —
/// <c>classid="{F9A8A302-114E-466A-B582-6771B2AE0D92}"</c> plus a <c>uniqueid</c> — and which
/// component actually renders is decided by a <c>&lt;controlDescription forControl="…"&gt;</c>
/// elsewhere in the document.</item>
/// <item>That description must declare <b>all three</b> form factors (0 web, 1 tablet, 2 phone),
/// or the designer rejects the form with
/// <c>Custom control declaration for form factor(s) 0,1,2 is missing</c>.</item>
/// <item>The component's name in FormXML is <c>customcontrol.name</c>, which carries the publisher
/// prefix the manifest does not: the manifest's <c>Contoso.DocumentViewer</c> is
/// <c>sample_Contoso.DocumentViewer</c> here. The manifest name alone fails with
/// <c>0x80160007 Custom control with name … does not exist</c>.</item>
/// <item>A bound control needs a column that is already <b>published</b>, otherwise the form write
/// fails with <c>0x80160051 Property boundField is bound to a non-existent attribute</c>.</item>
/// <item>A component whose manifest declares a bound property as <c>required</c> cannot be placed
/// unbound at all — that fails with
/// <c>0x80160032 Property boundField is required, but the declaration is missing</c>.</item>
/// </list>
/// The first three were verified against forms generated by the Maker portal; the fourth is as
/// reported from a live session.
/// <para>
/// Writes publish by default. Unlike table metadata, a form write is invisible without it — not
/// just to clients but to a read-back, because a <c>PATCH</c> writes the unpublished form while a
/// <c>GET</c> returns the published one.
/// </para>
/// </remarks>
public sealed partial class FormService
{
    private readonly DataverseHttpClient _client;
    private readonly PublishService _publish;
    private readonly ILogger<FormService> _logger;

    public FormService(DataverseHttpClient client, PublishService publish, ILogger<FormService> logger)
    {
        _client = client;
        _publish = publish;
        _logger = logger;
    }

    /// <summary>The generic classid every code component hosted in a cell uses.</summary>
    public const string CustomControlClassId = "{F9A8A302-114E-466A-B582-6771B2AE0D92}";

    /// <summary>Web, tablet and phone. A control description that omits one is rejected.</summary>
    private static readonly int[] FormFactors = [0, 1, 2];

    // ---------------------------------------------------------------------------------------------
    // Read
    // ---------------------------------------------------------------------------------------------

    public async Task<IReadOnlyList<FormSummary>> ListAsync(
        string orgUrl,
        string? tableLogicalName = null,
        int? type = null,
        CancellationToken ct = default)
    {
        var filters = new List<string>();
        if (!string.IsNullOrWhiteSpace(tableLogicalName))
            filters.Add($"objecttypecode eq '{tableLogicalName.Replace("'", "''")}'");
        if (type is not null)
            filters.Add($"type eq {type}");

        var url = "api/data/v9.2/systemforms"
                  + "?$select=formid,name,objecttypecode,type,formactivationstate,ismanaged,versionnumber"
                  + (filters.Count > 0 ? "&$filter=" + string.Join(" and ", filters) : string.Empty)
                  + "&$orderby=objecttypecode,name";

        var rows = await _client.GetAllPagesAsync(orgUrl, url, ct: ct);
        return [.. rows.Select(ToSummary)];
    }

    public async Task<FormDetail?> GetAsync(
        string orgUrl,
        Guid formId,
        bool includeFormXml = false,
        CancellationToken ct = default)
    {
        string raw;
        try
        {
            raw = await _client.GetRawAsync(
                orgUrl,
                $"api/data/v9.2/systemforms({formId:D})"
                + "?$select=formid,name,objecttypecode,type,formactivationstate,ismanaged,versionnumber,formxml",
                ct: ct);
        }
        catch (HttpRequestException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
        {
            return null;
        }

        using var doc = JsonDocument.Parse(raw);
        var root = doc.RootElement;
        var summary = ToSummary(root);
        var formXml = root.GetStringOrNull("formxml") ?? string.Empty;

        var (tabs, descriptions) = ParseFormXml(formXml);

        return new FormDetail(
            FormId: summary.FormId,
            Name: summary.Name,
            TableLogicalName: summary.TableLogicalName,
            Type: summary.Type,
            TypeName: summary.TypeName,
            FormActivationState: summary.FormActivationState,
            FormActivationStateName: summary.FormActivationStateName,
            IsManaged: summary.IsManaged,
            VersionNumber: summary.VersionNumber,
            Tabs: tabs,
            ControlDescriptions: descriptions,
            FormXml: includeFormXml ? formXml : null);
    }

    private static FormSummary ToSummary(JsonElement row)
    {
        var type = row.GetInt32OrZero("type");
        int? state = row.TryGetProperty("formactivationstate", out var s) && s.ValueKind == JsonValueKind.Number
            ? s.GetInt32()
            : null;

        long? version = row.TryGetProperty("versionnumber", out var v) && v.ValueKind == JsonValueKind.Number
            ? v.GetInt64()
            : null;

        return new FormSummary(
            FormId: row.TryGetGuid("formid"),
            Name: row.GetStringOrEmpty("name"),
            TableLogicalName: row.GetStringOrNull("objecttypecode"),
            Type: type,
            TypeName: MapFormType(type),
            FormActivationState: state,
            FormActivationStateName: state switch { 0 => "Inactive", 1 => "Active", null => null, _ => $"State{state}" },
            IsManaged: row.TryGetProperty("ismanaged", out var m) && m.ValueKind == JsonValueKind.True,
            VersionNumber: version);
    }

    /// <summary>Labels of the <c>systemform.type</c> choice.</summary>
    public static string MapFormType(int type) => type switch
    {
        0 => "Dashboard",
        1 => "AppointmentBook",
        2 => "Main",
        3 => "MiniCampaignBO",
        4 => "Preview",
        5 => "Mobile-Express",
        6 => "QuickViewForm",
        7 => "QuickCreate",
        8 => "Dialog",
        9 => "TaskFlowForm",
        10 => "InteractionCentricDashboard",
        11 => "Card",
        12 => "Main-InteractiveExperience",
        13 => "ContextualDashboard",
        _ => $"Type{type}"
    };

    /// <summary>
    /// Labels for the classids that turn up most. Unknown ones keep their GUID rather than being
    /// guessed at — the list is long and undocumented as a whole.
    /// </summary>
    private static string? MapClassId(string? classId) => classId?.ToUpperInvariant() switch
    {
        "{4273EDBD-AC1D-40D3-9FB2-095C621B552D}" => "Text",
        "{270BD3DB-D9AF-4782-9025-509E298DEC0A}" => "Lookup",
        "{F9A8A302-114E-466A-B582-6771B2AE0D92}" => "CustomControl",
        "{5B773807-9FB2-42DB-97C3-7A91EFF8ADFF}" => "DateTime",
        "{C6D124CA-7EDA-4A60-AEA9-7FB8D318B68F}" => "Integer",
        "{533B9E00-756B-4312-95A0-DC888637AC78}" => "Picklist",
        "{67FAC785-CD58-4F9F-ABB3-4B7DDC6ED5ED}" => "Radio",
        "{B0C6723A-8503-4FD7-BB28-C8A06AC933C2}" => "Checkbox",
        "{E0DECE4B-6FC8-4A8F-A065-082708572369}" => "TextArea",
        "{ADA2203E-B4CD-49BE-9DDF-234642B43B52}" => "URL",
        "{6F3FB987-393B-4D2D-859F-9D0F0349B6AD}" => "Money",
        "{E7A81278-8635-4D9E-8D4D-59480B391C5B}" => "SubGrid",
        "{9FDF5F91-88B1-47F4-AD53-C11EFC01A01D}" => "WebResource",
        "{5546E6CD-394C-4BEE-94A8-4425E17EF6C6}" => "Notes",
        "{62B0DF79-0464-470F-8AF7-4483CFEA0C7D}" => "IFrame",
        _ => null
    };

    /// <summary>
    /// Turn FormXML into the tree. Best-effort: a malformed document yields an empty structure
    /// rather than an exception, because a read of a broken form should still show its metadata.
    /// </summary>
    public static (IReadOnlyList<FormTab> Tabs, IReadOnlyList<FormControlDescription> Descriptions)
        ParseFormXml(string formXml)
    {
        if (string.IsNullOrWhiteSpace(formXml))
            return ([], []);

        XDocument doc;
        try
        {
            doc = XDocument.Parse(formXml);
        }
        catch (System.Xml.XmlException)
        {
            return ([], []);
        }

        var descriptions = doc.Descendants()
            .Where(e => e.Name.LocalName == "controlDescription")
            .Select(d => new FormControlDescription(
                ForControl: (string?)d.Attribute("forControl") ?? string.Empty,
                CustomControls: [.. d.Elements()
                    .Where(c => c.Name.LocalName == "customControl")
                    .Select(c => new FormCustomControl(
                        Name: (string?)c.Attribute("name") ?? string.Empty,
                        FormFactor: int.TryParse((string?)c.Attribute("formFactor"), out var ff) ? ff : null,
                        Parameters: c.Elements()
                            .Where(p => p.Name.LocalName == "parameters")
                            .SelectMany(p => p.Elements())
                            .GroupBy(p => p.Name.LocalName)
                            .ToDictionary(g => g.Key, g => g.First().Value)))]))
            .ToList();

        // A cell's control only carries a uniqueid; which component renders it lives in the
        // descriptions, so the two are joined here rather than left to the caller.
        var namesByUniqueId = descriptions
            .Where(d => !string.IsNullOrEmpty(d.ForControl))
            .ToDictionary(
                d => d.ForControl,
                d => (IReadOnlyList<string>)[.. d.CustomControls.Select(c => c.Name).Distinct()],
                StringComparer.OrdinalIgnoreCase);

        var tabs = doc.Descendants()
            .Where(e => e.Name.LocalName == "tab")
            .Select(tab => new FormTab(
                Id: (string?)tab.Attribute("id"),
                Name: (string?)tab.Attribute("name"),
                Label: FirstLabel(tab),
                Visible: !string.Equals((string?)tab.Attribute("visible"), "false", StringComparison.OrdinalIgnoreCase),
                Columns: [.. tab.Elements().Where(e => e.Name.LocalName == "columns")
                    .SelectMany(c => c.Elements().Where(e => e.Name.LocalName == "column"))
                    .Select(column => new FormColumn(
                        Width: (string?)column.Attribute("width"),
                        Sections: [.. column.Elements().Where(e => e.Name.LocalName == "sections")
                            .SelectMany(s => s.Elements().Where(e => e.Name.LocalName == "section"))
                            .Select(section => ParseSection(section, namesByUniqueId))]))]))
            .ToList();

        return (tabs, descriptions);
    }

    private static FormSection ParseSection(
        XElement section,
        IReadOnlyDictionary<string, IReadOnlyList<string>> namesByUniqueId) =>
        new(
            Id: (string?)section.Attribute("id"),
            Name: (string?)section.Attribute("name"),
            Label: FirstLabel(section),
            ShowLabel: string.Equals((string?)section.Attribute("showlabel"), "true", StringComparison.OrdinalIgnoreCase),
            Visible: !string.Equals((string?)section.Attribute("visible"), "false", StringComparison.OrdinalIgnoreCase),
            Cells: [.. section.Elements().Where(e => e.Name.LocalName == "rows")
                .SelectMany(r => r.Elements().Where(e => e.Name.LocalName == "row"))
                .SelectMany(r => r.Elements().Where(e => e.Name.LocalName == "cell"))
                .Select(cell => ParseCell(cell, namesByUniqueId))]);

    private static FormCell ParseCell(
        XElement cell,
        IReadOnlyDictionary<string, IReadOnlyList<string>> namesByUniqueId) =>
        new(
            Id: (string?)cell.Attribute("id"),
            Label: FirstLabel(cell),
            RowSpan: int.TryParse((string?)cell.Attribute("rowspan"), out var rs) ? rs : null,
            ColSpan: int.TryParse((string?)cell.Attribute("colspan"), out var cs) ? cs : null,
            Controls: [.. cell.Elements().Where(e => e.Name.LocalName == "control").Select(control =>
            {
                var classId = (string?)control.Attribute("classid");
                var uniqueId = (string?)control.Attribute("uniqueid");
                var isCustom = string.Equals(classId, CustomControlClassId, StringComparison.OrdinalIgnoreCase);

                IReadOnlyList<string> names = uniqueId is not null
                                              && namesByUniqueId.TryGetValue(uniqueId, out var found)
                    ? found
                    : [];

                return new FormControlInfo(
                    Id: (string?)control.Attribute("id"),
                    ClassId: classId,
                    ClassName: MapClassId(classId),
                    DataFieldName: (string?)control.Attribute("datafieldname"),
                    UniqueId: uniqueId,
                    IsUnbound: string.Equals((string?)control.Attribute("isunbound"), "true", StringComparison.OrdinalIgnoreCase),
                    IsCustomControl: isCustom,
                    CustomControlNames: names);
            })]);

    private static string? FirstLabel(XElement element) =>
        element.Elements().Where(e => e.Name.LocalName == "labels")
            .SelectMany(l => l.Elements().Where(e => e.Name.LocalName == "label"))
            .Select(l => (string?)l.Attribute("description"))
            .FirstOrDefault(d => !string.IsNullOrEmpty(d));
}
