namespace Dataverse.Core.Workflows;

using System.Xml.Linq;
using static Dataverse.Core.Workflows.WorkflowXamlNames;

/// <summary>
/// Parses Classic Workflow WF4 XAML into a best-effort <see cref="WorkflowInterpretation"/>.
/// Two jobs: (1) produce a human-readable description of any workflow, and (2) decide whether
/// a workflow is "simple enough" to be safely re-generated by the MCP (the edit gate). Unknown
/// activities never throw — they are reported as <c>Unknown</c> steps.
/// </summary>
public static class WorkflowXamlParser
{
    public static WorkflowInterpretation Interpret(string? xaml)
    {
        if (string.IsNullOrWhiteSpace(xaml))
            return new WorkflowInterpretation(false, null, false, [], ["XAML is empty."]);

        XDocument doc;
        try
        {
            doc = XDocument.Parse(xaml);
        }
        catch (Exception ex)
        {
            return new WorkflowInterpretation(false, null, false, [], [$"XAML is not well-formed: {ex.Message}"]);
        }

        var notes = new List<string>();
        var root = doc.Root;
        if (root is null || root.Name != Activities + "Activity")
            return new WorkflowInterpretation(false, null, false, [], ["Root <Activity> element not found."]);

        var className = root.Attribute(X + "Class")?.Value;

        var workflow = root.Element(Mxswa + "Workflow");
        if (workflow is null)
            return new WorkflowInterpretation(true, className, false, [], ["No <mxswa:Workflow> body found."]);

        var steps = new List<InterpretedStep>();
        foreach (var child in workflow.Elements())
        {
            if (child.Name == Mxswa + "Workflow.Variables")
                continue;
            steps.Add(ClassifyStep(child, notes));
        }

        var recognized = steps.Count > 0 && steps.All(s =>
            s.Kind is "UpdateEntity" or "CreateEntity" or "CustomActivity");

        if (steps.Count == 0)
            notes.Add("Workflow has no steps.");

        return new WorkflowInterpretation(true, className, recognized, steps, notes);
    }

    private static InterpretedStep ClassifyStep(XElement el, List<string> notes)
    {
        // Sequence-based steps: Update or Create entity.
        if (el.Name == Activities + "Sequence")
        {
            var update = el.Descendants(Mxswa + "UpdateEntity").FirstOrDefault();
            if (update is not null)
                return DescribeEntityWrite(el, update, "UpdateEntity", "Updates");

            var create = el.Descendants(Mxswa + "CreateEntity").FirstOrDefault();
            if (create is not null)
                return DescribeEntityWrite(el, create, "CreateEntity", "Creates");

            var display = el.Attribute("DisplayName")?.Value ?? "Sequence";
            notes.Add($"Sequence '{display}' contains no recognised Create/Update activity.");
            return new InterpretedStep("Unknown", $"Unrecognised sequence '{display}'.");
        }

        // ActivityReference-based steps.
        if (el.Name == Mxswa + "ActivityReference")
        {
            var aqn = el.Attribute("AssemblyQualifiedName")?.Value ?? "";

            if (aqn.StartsWith(CompositeAqnPrefix, StringComparison.Ordinal))
            {
                var custom = FindCustomActivity(el);
                if (custom is not null)
                {
                    var customAqn = custom.Attribute("AssemblyQualifiedName")?.Value ?? "";
                    var args = custom.Element(Mxswa + "ActivityReference.Arguments")?
                        .Elements()
                        .Select(a => a.Attribute(X + "Key")?.Value ?? "?")
                        .ToList() ?? [];
                    var typeName = customAqn.Split(',').FirstOrDefault()?.Trim() ?? customAqn;
                    return new InterpretedStep(
                        "CustomActivity",
                        $"Calls custom activity '{typeName}' with {args.Count} argument(s).",
                        AssemblyQualifiedName: customAqn,
                        Arguments: args);
                }

                notes.Add("Composite block without an identifiable custom activity.");
                return new InterpretedStep("Unknown", "Composite block (no custom activity identified).");
            }

            if (aqn.StartsWith(ConditionSequenceAqnPrefix, StringComparison.Ordinal))
                return new InterpretedStep("Condition", "Conditional branch (Check Condition). Not regenerable by the MCP.");

            var refType = aqn.Split(',').FirstOrDefault()?.Trim() ?? aqn;
            return new InterpretedStep("Unknown", $"Activity reference '{refType}'.");
        }

        return new InterpretedStep("Unknown", $"Element '{el.Name.LocalName}'.");
    }

    private static InterpretedStep DescribeEntityWrite(XElement seq, XElement writeActivity, string kind, string verb)
    {
        var entity = writeActivity.Attribute("EntityName")?.Value
                     ?? seq.Descendants(Mxswa + "SetEntityProperty").FirstOrDefault()?.Attribute("EntityName")?.Value
                     ?? "?";
        var fields = seq.Descendants(Mxswa + "SetEntityProperty")
            .Select(s => s.Attribute("Attribute")?.Value ?? "?")
            .ToList();
        return new InterpretedStep(
            kind,
            $"{verb} '{entity}' and sets {fields.Count} field(s): {string.Join(", ", fields)}.",
            EntityName: entity,
            Fields: fields);
    }

    /// <summary>
    /// Finds the inner ActivityReference of a Composite that points at a non-built-in (custom) activity.
    /// </summary>
    private static XElement? FindCustomActivity(XElement composite)
    {
        var activities = composite
            .Element(Mxswa + "ActivityReference.Properties")?
            .Elements(Sco + "Collection")
            .FirstOrDefault(c => c.Attribute(X + "Key")?.Value == "Activities");

        if (activities is null)
            return null;

        return activities.Elements(Mxswa + "ActivityReference")
            .FirstOrDefault(a =>
            {
                var aqn = a.Attribute("AssemblyQualifiedName")?.Value ?? "";
                return !aqn.StartsWith("Microsoft.Crm.Workflow.", StringComparison.Ordinal)
                       && !aqn.StartsWith("Microsoft.Xrm.Sdk.Workflow", StringComparison.Ordinal);
            });
    }

    // AQN prefixes (type + assembly portion, version-independent) for robust matching.
    private const string CompositeAqnPrefix = "Microsoft.Crm.Workflow.Activities.Composite, Microsoft.Crm.Workflow";
    private const string ConditionSequenceAqnPrefix = "Microsoft.Crm.Workflow.Activities.ConditionSequence, Microsoft.Crm.Workflow";
}
